version: '2'

services:
  mongodb:
    image: mongo
    expose:
      - 27017
    networks:
      coop:
        aliases: [mongodb]
  coop-api:
    build: api
    depends_on: [mongodb]
    expose:
      - 80
    networks:
      coop: {}
      server_nginx:
        aliases: [coop-api]
networks:
  coop:
    driver: bridge
  server_nginx:
    external: true
